

GET http://localhost:3333


###
POST http://localhost:3333/cars/register
content-Type: application/json

{
    "avaible": "Sim",
    "hireCar": "Disponivel para alugar",
    "modelCar": "Gol",
    "colorCar": "Branco",
    "fabCar": "Volkswagem"
}

###
POST http://localhost:3333/client/register
content-Type: application/json

{
    "name": "teste2",
    "email": "testedelete@gmail.com",
    "CPF": "000.000.000-01",
    "CEP": "98960000",
    "numberPhone": "55 01234-5678"
}

###

DELETE http://localhost:3333/client/2

###

PUT http://localhost:3333/client/1
content-Type: application/json

{
    "name": "teste4",
    "email": "testeupdate@gmail.com",
    "CPF": "000.000.000-03",
    "CEP": "98960006",
    "numberPhone": "55 01234-5679"
}

###